# Generated by Django 5.1.3 on 2024-12-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(max_length=4000),
        ),
    ]
