# Generated by Django 5.1.3 on 2024-12-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0003_livro_capa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=4000)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/')),
            ],
        ),
    ]
