# Generated by Django 5.1.3 on 2024-12-02 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0004_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor_livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='app_livraria.autor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='app_livraria.livro')),
            ],
            options={
                'db_table': 'autor_livro',
                'unique_together': {('autor', 'livro')},
            },
        ),
    ]
