# Generated by Django 5.1.3 on 2024-12-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0009_pasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='capa',
            field=models.ImageField(blank=True, default='capas_pastas/default.jpg', null=True, upload_to='capas_pastas/'),
        ),
    ]
