# Generated by Django 5.1.3 on 2024-12-05 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0012_alter_pasta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasta',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
