# Generated by Django 5.1.3 on 2024-12-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0013_pasta_created_pasta_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasta',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.CreateModel(
            name='Pasta_livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='app_livraria.livro')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='app_livraria.pasta')),
            ],
        ),
    ]
