# Generated by Django 5.1.3 on 2024-12-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_livraria.pasta'),
        ),
    ]
