# Generated by Django 5.1.3 on 2024-12-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0019_alter_profile_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pasta_livro',
            unique_together={('pasta', 'livro')},
        ),
    ]
